//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("fixeol ver:1.4.31114.3")]
[assembly: System.Reflection.AssemblyDescription("fixes the eol (end of line) characters for the specified file.")]
[assembly: System.Reflection.AssemblyCompany("Bricksoft.com")]
[assembly: System.Reflection.AssemblyProduct("fixeol")]
[assembly: System.Reflection.AssemblyCopyright("Copyright (C) 2008-2013 Kody Brown.")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(false)]
[assembly: System.Runtime.InteropServices.Guid("E8043946-8131-4319-B9EF-E36FA6726B2A")]
[assembly: System.Reflection.AssemblyVersion("1.4.31114.3")]
[assembly: System.Reflection.AssemblyFileVersion("1.4.31114.3")]


