name: dotnet-core-build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get source
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore fixeol.slnx

      - name: Build
        run: dotnet build fixeol.slnx --configuration Release --no-restore

      - name: Test
        run: dotnet test fixeol.slnx --configuration Release --no-build --verbosity normal
