name: fixeol build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        dotnet: [ '2.2.x', '3.0', '3.1.x' ]
    name: Dotnet ${{ matrix.dotnet }}
    steps:
      - name: Get source
        uses: actions/checkout@master
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
#       - run: dotnet restore
          
#       - name: Restore
#         run: dotnet restore
        
#       - name: Build
#       - run: dotnet build --no-restore --configuration Release
      - run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Publish
        run: dotnet publish --no-restore --configuration Release
