name: dotnet-core-release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # dotnet: [ '2.2.x', '3.0', '3.1.x' ]
        dotnet: [ '3.1.202' ]
    name: dotnet core ${{ matrix.dotnet }}
    steps:
      - name: Get tag
        run: |
          echo ::set-env name=TAG_NAME::${GITHUB_REF#refs/*/}
          echo TAG_NAME=${{ env.TAG_NAME }}

      - name: Get source
        uses: actions/checkout@master

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.4.0
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ env.TAG_NAME }}
          draft: false
          prerelease: false

      - name: Publish win-x64
        run: |
          dotnet publish --nologo --no-restore --no-build --configuration Release --runtime win-x64 --framework netcoreapp3.1 --output ./publish/win-x64/ --self-contained false
          zip --junk-paths ./fixeol-win_x64-${{ env.TAG_NAME }}.zip ./publish/win-x64/*

      - name: Upload Release win-x64
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./fixeol-win_x64-${{ env.TAG_NAME }}.zip
          asset_name: fixeol-win_x64-${{ env.TAG_NAME }}.zip
          asset_content_type: application/zip

      - name: Publish linux-x64
        run: |
          dotnet publish --nologo --no-restore --no-build --configuration Release --runtime linux-x64 --framework netcoreapp3.1 --output ./publish/linux-x64/ --self-contained false
          zip --junk-paths ./fixeol-linux_x64-${{ env.TAG_NAME }}.zip ./publish/linux-x64/*

      - name: Upload Release linux-x64
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./fixeol-linux_x64-${{ env.TAG_NAME }}.zip
          asset_name: fixeol-linux_x64-${{ env.TAG_NAME }}.zip
          asset_content_type: application/zip
