name: fixeol build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    #runs-on: ubuntu-16.04
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #dotnet: [ '2.2.x', '3.0', '3.1.x' ]
        dotnet: [ '3.1.100' ]
    name: Dotnet ${{ matrix.dotnet }}
    steps:
      - name: Get the source
      - uses: actions/checkout@master
        
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.4.0
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - run: dotnet build -c Release

#       - name: Restore
#       - run: dotnet restore
          
#       - name: Restore
#         run: dotnet restore
        
#       - name: Build
#       - run: dotnet build --no-restore --configuration Release

#       - name: Test
#         run: dotnet test --no-restore --verbosity normal

#       - name: Publish
#         run: dotnet publish --no-restore --configuration Release
